name: 'Cluster - Plan and Destroy'

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  Terraform:
    uses: perrness/reusable-workflows/.github/workflows/azure-plan-and-destroy.yaml@main
    with:
      working_directory: ./cluster
      default_storage_key: false
      terraform_args: >-
        -var-file="../config.tfvars"
    secrets: inherit
